### ISSUE TITLE
Twitter bar

### ISSUE THREAD

**Issue by tigerhawkvok** [tigerhawkvok/asm-mammal-database#32]
Via @n8upham @27:

>Also, is adding a Twitter bar a difficult thing to do?  I'm modeling this idea after the WoRMS database: http://www.marinespecies.org/

**Comment by tigerhawkvok** [comment]
I think I'm going to use something like a flyout to contain this -- having it live on the front page problematic for spacing reasons.

For example, take a look at the WoRMS page on a smaller screen:

![image](https://user-images.githubusercontent.com/165937/27014459-4b77f7be-4eae-11e7-8972-514a597752ab.png)

or a mobile phone:

![image](https://user-images.githubusercontent.com/165937/27014473-79fb3f9c-4eae-11e7-97c9-a374b659dd2a.png)



All the content is basically unusable.

In contrast, a flyout preserves data density on a desktop:

![image](https://user-images.githubusercontent.com/165937/27014494-e47e4206-4eae-11e7-81ce-63d776912559.png)

![image](https://user-images.githubusercontent.com/165937/27014489-c8b81d12-4eae-11e7-8135-3b5c716c644f.png)


as well as smaller screens:

![image](https://user-images.githubusercontent.com/165937/27014498-f57e1cb6-4eae-11e7-9b17-cd5763a76efa.png)

and mobile, too:

![image](https://user-images.githubusercontent.com/165937/27014540-acc30b84-4eaf-11e7-9143-41e50ea1d416.png)

![image](https://user-images.githubusercontent.com/165937/27014541-b87e6eaa-4eaf-11e7-9af9-a729b338939d.png)

**Comment by n8upham** [comment]
I dig it man!! Yes the flyout is key for mobile especially. Glad you are thinking along those lines for future portability. Gracias--n


Sent on my Samsung Galaxy S® 5

-------- Original message --------
