### ISSUE TITLE
Advanced searching vs. all-in-one searching

### ISSUE THREAD

**Issue by n8upham** [tigerhawkvok/asm-mammal-database#46]
How much work is involved in making the main search field == a query to all fields in the database?  Would there be a cost of longer search times? 

Also, when I search "Rodentia" under "Clade" the advanced search still returns no results.  I think we want Clade to indicate Higher Taxon in general

Genus Authority does work (e.g., "Thomas" returns 8 results), but species authority returns no results for the same search...

Thanks, --n

**Comment by tigerhawkvok** [comment]
Sorry -- I didn't upload the new index, just the support files for the fix (remember my email about Git making sure I got all the right files? see this!).

The advanced search fields have been relabelled to make it clearer. (`rodentia` works if put in the `linnean order` column -- the previous entry fields were actually misaligned and not "pointing" where they should).


![image](https://cloud.githubusercontent.com/assets/165937/26765358/673c1a18-492f-11e7-8083-6d6c2db0a370.png)




Right now I'm getting 822 results for "thomas" for species authority:

![image](https://cloud.githubusercontent.com/assets/165937/26765348/3680b00a-492f-11e7-941c-afb7cb36fce5.png)


as well as your 8 for genus:

![image](https://cloud.githubusercontent.com/assets/165937/26765352/4d7cc316-492f-11e7-9564-a5b07a166e3c.png)


I can add a toggle to search all columns -- the search time difference is going to be basically nothing (the actual query itself is a very very small fraction of the whole search process, << 0.1s). The original design decision was mostly just that it can get very "dirty" results.

**Comment by n8upham** [comment]
OK Philip this is awesome— big thanks for instituting those changes.

One quick thing: Can you make the “default” to have the All Fields search turned on?  Seems best to have folks get lots of results initially, and then winnow them down as needed with more advanced fields.

Also, can we move up the box where it says "Search for a common or scientific name above to begin, eg, "Brown Bear" or "Ursus arctos” “ — Ideally underneath the “Search” line and above the “Options” section.

Thanks much
—n

**Comment by tigerhawkvok** [comment]
That's a quick and easy fix - I'll try to get to it this evening.

_Sent from my Huawei Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
