### ISSUE TITLE
"Featured Mammal" on the front page

### ISSUE THREAD

**Issue by tigerhawkvok** [tigerhawkvok/asm-mammal-database#51]
Via @n8upham 

> Featured mammal = one of these 4 species with free Mammalian Species accounts: https://academic.oup.com/mspecies/pages/speciesaccounts
>
>- The goal here is to 
>   1.  showcase this ASM-based journal, and 
>   2. make an argument to the Board that we should be serving the content of these Mammalian Species articles *for free* on the MDD website.  This would both populate our per-species pages and provide an outlet to these articles that often linger in obscurity, but contain much valuable information
>- Check out that Felis margarita! 

My initial response and thoughts:

>I will need to ponder the featured mammal entry -- need to figure out a way to both accomplish the goal above and to keep search functions central and accessible.  
>
>My best off-the-cuff idea is an auto-opening dialog on first visit / featured taxon change, with some other button or iconography to expose it again manually (so it shows up immediately when it's new to you, but when you're going to the site to do a "routine" search you're not interrupted by content you've already seen before). 
>
>There may be a better solution, just I haven't thought of it yet.

Later response:

>Yes I like the idea of a featured mammal tab that is popped out the first time, but not on subsequent visits.  But maybe on the pop-out tab there can still be a small (thumbnail) version of the MIL image for that featured species?  I want to have some mammal images on the front page, so people know there are here to learn about furry things!

**Comment by tigerhawkvok** [comment]
Mock:

![image](https://user-images.githubusercontent.com/165937/27167794-6f0b378a-5157-11e7-9882-3a7fd153c4b6.png)

**Comment by n8upham** [comment]
I'd say use a minicard with image for the featured mammal-- we need to get some mammal images on that front page.  Maybe sized as a box matching the ASM antelope logo on the left?  Symmetry is always good.  And Felix margarita is super cute...

**Comment by n8upham** [comment]
This looks cool so far!  I notice that the cursor does not change to a "hand" the same was as it does over the Twitter scroll, so perhaps folks won't know to click it?

Also, can we add the full text of this Mammalian Species account to the featured page, to show folks how this could look?  Its open access so should be okay for now... https://academic.oup.com/mspecies/article/47/924/63/2609388/Felis-margarita-Carnivora-Felidae?searchresult=1

**Comment by tigerhawkvok** [comment]
I initially had some text, but broke it at some point during the past two days - just need to re add it. (Everything got lower cased, blegh)

_Sent from my Huawei Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by tigerhawkvok** [comment]
I want to eventually change this generation to a random entry from the ten longest, newest entries with an image rather than statically filled.

_Sent from my Huawei Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by n8upham** [comment]
OK sounds good!

**Comment by tigerhawkvok** [comment]
yeah, I'll end up splitting the "eventually" to a new issue rather than targeting that for tomorrow (!) especially since there won't be enough data populated by then to make it really do anything different.
