### ISSUE TITLE
A dino!

### ISSUE THREAD

**Issue by n8upham** [tigerhawkvok/asm-mammal-database#61]
Connor found this one:
https://mammaldiversity.org/species-account.php?genus=utahraptor&species=ostrommaysorum

I'm working on arranging the final list now... more soon
--n

**Comment by tigerhawkvok** [comment]
Hah! Test taxon, clearly.

Going to my girlfriend's PhD commencement today, so I'll be MIA (mostly) till tomorrow.

_Sent from my Huawei Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by tigerhawkvok** [comment]
Fixed at 57b4428646e4458a50a8a04b064f08c5dccecc68
