### ISSUE TITLE
Advanced search bug -- from ASM Comm Members #1

### ISSUE THREAD

**Issue by n8upham** [tigerhawkvok/asm-mammal-database#65]
"I was able to break the search by searching using the advanced options alone (nothing in the standard search box), all my queries returned the entire database. It might be better to label the advanced options as "filters" to narrow down the search results? Or perhaps just refuse to search if the standard search line is blank? I'm not sure which would be an easier fix. "

**Comment by tigerhawkvok** [comment]
Good catch. It's supposed to behave that way, might be an interaction with the "all fields" toggle (if so, I can have that auto uncheck on opening advanced)

_Sent from my Huawei Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
