### ISSUE TITLE
Taxon statistics page -- from ASM Comm Members #4

### ISSUE THREAD

**Issue by n8upham** [tigerhawkvok/asm-mammal-database#68]
"On the statistics page, species diversity is plotted as a bar graph (appropriate), but generic diversity is plotted as a filled curve (not ideal). Let’s set a good example of appropriate use of graphs and use bar graphs for both categories."

Maybe side-by-side bar graphs, just slightly to the left or right for genera?

Thanks man (that was the last one!)

**Comment by tigerhawkvok** [comment]
Two different charts, or two bars per order?

_Sent from my Huawei Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by n8upham** [comment]
I’d say two bars per order—one for species and one for genera— and then have the genus one slightly “gittered” to the right so as to understand that two bars are present.  If that’s a difficult thing in this interface, then maybe only keep a big filled dot for genus diversity on the species bar chart per order.  
Thanks

**Comment by tigerhawkvok** [comment]
Twin bars:

![image](https://user-images.githubusercontent.com/165937/27264914-335a6130-543f-11e7-8de7-42566cfee7e8.png)

**Comment by n8upham** [comment]
Looks awesome man, perfect!
—n
